title: Patrik Bey webpage
description: This site highlights the projects I've been working on in the past and those that are still WIP.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme